-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."dimCompany"
(
    company_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimCompany_pkey" PRIMARY KEY (company_id),
    CONSTRAINT "dimCompany_url_key" UNIQUE (url)
);

CREATE TABLE IF NOT EXISTS public."dimDate"
(
    date_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date date,
    day integer,
    month_id integer NOT NULL,
    year_id integer NOT NULL,
    weekday_id integer NOT NULL,
    quarter_id integer NOT NULL,
    CONSTRAINT "dimDate_pkey" PRIMARY KEY (date_id),
    CONSTRAINT "dimDate_date_key" UNIQUE (date)
);

CREATE TABLE IF NOT EXISTS public."dimExperience"
(
    experience_required_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    experience character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimExperience_pkey" PRIMARY KEY (experience_required_id),
    CONSTRAINT "dimExperience_experience_key" UNIQUE (experience)
);

CREATE TABLE IF NOT EXISTS public."dimListing_dimSubcategories"
(
    "dimListing_listing_id" integer NOT NULL,
    "dimSubcategories_subcat_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."dimLocation"
(
    location_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    country character varying COLLATE pg_catalog."default" DEFAULT 'Israel'::character varying,
    CONSTRAINT "dimLocation_pkey" PRIMARY KEY (location_id),
    CONSTRAINT "dimLocation_name_key" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public."dimMonth"
(
    month_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimMonth_pkey" PRIMARY KEY (month_id)
);

CREATE TABLE IF NOT EXISTS public."dimPositionType"
(
    type_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_type character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimPositionType_pkey" PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS public."dimQuarter"
(
    quarter_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimQuarter_pkey" PRIMARY KEY (quarter_id)
);

CREATE TABLE IF NOT EXISTS public."dimSource"
(
    source_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimSource_pkey" PRIMARY KEY (source_id)
);

CREATE TABLE IF NOT EXISTS public."dimSubcategories"
(
    subcat_id integer NOT NULL,
    category_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    internal_id integer,
    CONSTRAINT "dimSubcategories_pkey" PRIMARY KEY (subcat_id)
);

CREATE TABLE IF NOT EXISTS public."dimWeekday"
(
    weekday_id integer NOT NULL,
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT "dimWeekday_pkey" PRIMARY KEY (weekday_id)
);

CREATE TABLE IF NOT EXISTS public."dimYear"
(
    year_id integer NOT NULL,
    year integer,
    CONSTRAINT "dimYear_pkey" PRIMARY KEY (year_id),
    CONSTRAINT "dimYear_year_key" UNIQUE (year)
);

CREATE TABLE IF NOT EXISTS public."listingFacts"
(
    listing_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    category_id integer NOT NULL,
    link character varying COLLATE pg_catalog."default",
    title character varying COLLATE pg_catalog."default",
    company_id integer NOT NULL,
    experience_required_id integer NOT NULL,
    description character varying COLLATE pg_catalog."default",
    requirements character varying COLLATE pg_catalog."default",
    salary_range character varying COLLATE pg_catalog."default",
    phone_number character varying COLLATE pg_catalog."default",
    location_id integer,
    type_id integer,
    date_id integer,
    "timestamp" timestamp without time zone DEFAULT now(),
    CONSTRAINT "dimListing_pkey" PRIMARY KEY (listing_id),
    CONSTRAINT link UNIQUE (link)
);

ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_month_id_fkey" FOREIGN KEY (month_id)
    REFERENCES public."dimMonth" (month_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_month_id_fkey1" FOREIGN KEY (month_id)
    REFERENCES public."dimMonth" (month_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_quarter_id_fkey" FOREIGN KEY (quarter_id)
    REFERENCES public."dimQuarter" (quarter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_quarter_id_fkey1" FOREIGN KEY (quarter_id)
    REFERENCES public."dimQuarter" (quarter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_weekday_id_fkey" FOREIGN KEY (weekday_id)
    REFERENCES public."dimWeekday" (weekday_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_weekday_id_fkey1" FOREIGN KEY (weekday_id)
    REFERENCES public."dimWeekday" (weekday_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_year_id_fkey" FOREIGN KEY (year_id)
    REFERENCES public."dimYear" (year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimDate"
    ADD CONSTRAINT "dimDate_year_id_fkey1" FOREIGN KEY (year_id)
    REFERENCES public."dimYear" (year_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimListing_dimSubcategories"
    ADD CONSTRAINT "dimListing_dimSubcategories_dimListing_listing_id_fkey" FOREIGN KEY ("dimListing_listing_id")
    REFERENCES public."listingFacts" (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."dimListing_dimSubcategories"
    ADD CONSTRAINT "dimListing_dimSubcategories_dimSubcategories_subcat_id_fkey" FOREIGN KEY ("dimSubcategories_subcat_id")
    REFERENCES public."dimSubcategories" (subcat_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "dimListing_company_id_fkey" FOREIGN KEY (company_id)
    REFERENCES public."dimCompany" (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "dimListing_company_id_fkey1" FOREIGN KEY (company_id)
    REFERENCES public."dimCompany" (company_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "dimListing_experience_required_id_fkey" FOREIGN KEY (experience_required_id)
    REFERENCES public."dimExperience" (experience_required_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "dimListing_experience_required_id_fkey1" FOREIGN KEY (experience_required_id)
    REFERENCES public."dimExperience" (experience_required_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "dimListing_type_id_fkey" FOREIGN KEY (type_id)
    REFERENCES public."dimPositionType" (type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."listingFacts"
    ADD CONSTRAINT "listingFacts_date_id_fkey" FOREIGN KEY (date_id)
    REFERENCES public."dimDate" (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
